export const data = [
  {
    id: 1,
    fullName: "Leanne Graham",
    userName: "Bret",
    email: "Sincere@april.biz",
    phoneNumber: "1-770-736-8031 x56442",
    website: "hildegard.org",
    companyName: "Romaguera-Crona",
  },
  {
    id: 2,
    fullName: "Ervin Howell",
    userName: "Antonette",
    email: "Shanna@melissa.tv",
    phoneNumber: "010-692-6593 x09125",
    website: "anastasia.net",
    companyName: "Deckow-Crist",
  },
  {
    id: 3,
    fullName: "Clementine Bauch",
    userName: "Samantha",
    email: "Nathan@yesenia.net",
    phoneNumber: "1-463-123-4447",
    website: "ramiro.info",
    companyName: "Romaguera-Jacobson",
  },
  {
    id: 4,
    fullName: "Patricia Lebsack",
    userName: "Karianne",
    email: "Julianne.OConner@kory.org",
    phoneNumber: "493-170-9623 x156",
    website: "kale.biz",
    companyName: "Robel-Corkery",
  },
  {
    id: 5,
    fullName: "Chelsey Dietrich",
    userName: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    phoneNumber: "(254)954-1289",
    website: "demarco.info",
    companyName: "Keebler LLC",
  },
  {
    id: 6,
    fullName: "Mrs. Dennis Schulist",
    userName: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    phoneNumber: "1-477-935-8478 x6430",
    website: "ola.org",
    companyName: "Considine-Lockman",
  },
  {
    id: 7,
    fullName: "Kurtis Weissnat",
    userName: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    phoneNumber: "210.067.6132",
    website: "elvis.io",
    companyName: "Johns Group",
  },
  {
    id: 8,
    fullName: "Nicholas Runolfsdottir V",
    userName: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    phoneNumber: "586.493.6943 x140",
    website: "jacynthe.com",
    companyName: "Abernathy Group",
  },
  {
    id: 9,
    fullName: "Glenna Reichert",
    userName: "Delphine",
    email: "Chaim_McDermott@dana.io",
    phoneNumber: "(775)976-6794 x41206",
    website: "conrad.com",
    companyName: "Yosting Mantra",
  },
  {
    id: 10,
    fullName: "Clementina DuBuque",
    userName: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    phoneNumber: "024-648-3804",
    website: "ambrose.net",
    companyName: "Hoeger LLC",
  },
];
