export const data = [
  {
    id: 1,
    fullName: "Leanne Graham",
    userName: "Bret",
    email: "Sincere@april.biz",
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
      zipcode: "92998-3874",
    },
    phoneNumber: "1-770-736-8031 x56442",
    website: "hildegard.org",
    companyName: "Romaguera-Crona",
  },
  {
    id: 2,
    fullName: "Ervin Howell",
    userName: "Antonette",
    email: "Shanna@melissa.tv",
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
      zipcode: "90566-7771",
    },
    phoneNumber: "010-692-6593 x09125",
    website: "anastasia.net",
    companyName: "Deckow-Crist",
  },
  {
    id: 3,
    fullName: "Clementine Bauch",
    userName: "Samantha",
    email: "Nathan@yesenia.net",
    address: {
      street: "Douglas Extension",
      suite: "Suite 847",
      city: "McKenziehaven",
      zipcode: "59590-4157",
    },
    phoneNumber: "1-463-123-4447",
    website: "ramiro.info",
    companyName: "Romaguera-Jacobson",
  },
  {
    id: 4,
    fullName: "Patricia Lebsack",
    userName: "Karianne",
    email: "Julianne.OConner@kory.org",
    address: {
      street: "Hoeger Mall",
      suite: "Apt. 692",
      city: "South Elvis",
      zipcode: "53919-4257",
    },
    phoneNumber: "493-170-9623 x156",
    website: "kale.biz",
    companyName: "Robel-Corkery",
  },
  {
    id: 5,
    fullName: "Chelsey Dietrich",
    userName: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    address: {
      street: "Skiles Walks",
      suite: "Suite 351",
      city: "Roscoeview",
      zipcode: "33263",
    },
    phoneNumber: "(254)954-1289",
    website: "demarco.info",
    companyName: "Keebler LLC",
  },
  {
    id: 6,
    fullName: "Mrs. Dennis Schulist",
    userName: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    address: {
      street: "Norberto Crossing",
      suite: "Apt. 950",
      city: "South Christy",
      zipcode: "23505-1337",
    },
    phoneNumber: "1-477-935-8478 x6430",
    website: "ola.org",
    companyName: "Considine-Lockman",
  },
  {
    id: 7,
    fullName: "Kurtis Weissnat",
    userName: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    address: {
      street: "Rex Trail",
      suite: "Suite 280",
      city: "Howemouth",
      zipcode: "58804-1099",
    },
    phoneNumber: "210.067.6132",
    website: "elvis.io",
    companyName: "Johns Group",
  },
  {
    id: 8,
    fullName: "Nicholas Runolfsdottir V",
    userName: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    address: {
      street: "Ellsworth Summit",
      suite: "Suite 729",
      city: "Aliyaview",
      zipcode: "45169",
    },
    phoneNumber: "586.493.6943 x140",
    website: "jacynthe.com",
    companyName: "Abernathy Group",
  },
  {
    id: 9,
    fullName: "Glenna Reichert",
    userName: "Delphine",
    email: "Chaim_McDermott@dana.io",
    address: {
      street: "Dayna Park",
      suite: "Suite 449",
      city: "Bartholomebury",
      zipcode: "76495-3109",
    },
    phoneNumber: "(775)976-6794 x41206",
    website: "conrad.com",
    companyName: "Yosting Mantra",
  },
  {
    id: 10,
    fullName: "Clementina DuBuque",
    userName: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    address: {
      street: "Kattie Turnpike",
      suite: "Suite 198",
      city: "Lebsackbury",
      zipcode: "31428-2261",
    },
    phoneNumber: "024-648-3804",
    website: "ambrose.net",
    companyName: "Hoeger LLC",
  },
];


